// <auto-generated />
using System;
using Diploma.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diploma.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Diploma.Entity.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("axis");

                    b.Property<long>("MeasurementId")
                        .HasColumnType("bigint")
                        .HasColumnName("measurement_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<DateTime>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("triggered_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Diploma.Entity.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BaselineReady")
                        .HasColumnType("boolean")
                        .HasColumnName("baseline_ready");

                    b.Property<long>("DeviceTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("device_ts");

                    b.Property<int>("PacketNumber")
                        .HasColumnType("integer")
                        .HasColumnName("packet_number");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("X_Bear")
                        .HasColumnType("double precision")
                        .HasColumnName("x_bear");

                    b.Property<double>("X_Crest")
                        .HasColumnType("double precision")
                        .HasColumnName("x_crest");

                    b.Property<double>("X_Freq")
                        .HasColumnType("double precision")
                        .HasColumnName("x_freq");

                    b.Property<double>("X_Gear")
                        .HasColumnType("double precision")
                        .HasColumnName("x_gear");

                    b.Property<double>("X_Rms")
                        .HasColumnType("double precision")
                        .HasColumnName("x_rms");

                    b.Property<double>("Y_Bear")
                        .HasColumnType("double precision")
                        .HasColumnName("y_bear");

                    b.Property<double>("Y_Crest")
                        .HasColumnType("double precision")
                        .HasColumnName("y_crest");

                    b.Property<double>("Y_Freq")
                        .HasColumnType("double precision")
                        .HasColumnName("y_freq");

                    b.Property<double>("Y_Gear")
                        .HasColumnType("double precision")
                        .HasColumnName("y_gear");

                    b.Property<double>("Y_Rms")
                        .HasColumnType("double precision")
                        .HasColumnName("y_rms");

                    b.Property<double>("Z_Bear")
                        .HasColumnType("double precision")
                        .HasColumnName("z_bear");

                    b.Property<double>("Z_Crest")
                        .HasColumnType("double precision")
                        .HasColumnName("z_crest");

                    b.Property<double>("Z_Freq")
                        .HasColumnType("double precision")
                        .HasColumnName("z_freq");

                    b.Property<double>("Z_Gear")
                        .HasColumnType("double precision")
                        .HasColumnName("z_gear");

                    b.Property<double>("Z_Rms")
                        .HasColumnType("double precision")
                        .HasColumnName("z_rms");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_measurements_received_at");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("Diploma.Entity.ThresholdConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Metric")
                        .IsUnique()
                        .HasDatabaseName("ix_thresholds_metric");

                    b.ToTable("thresholds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Metric = "crest",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Metric = "bearing",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 0.050000000000000003
                        },
                        new
                        {
                            Id = 3,
                            Metric = "gear",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 0.050000000000000003
                        });
                });

            modelBuilder.Entity("Diploma.Entity.Alert", b =>
                {
                    b.HasOne("Diploma.Entity.Measurement", "Measurement")
                        .WithMany("Alerts")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Diploma.Entity.Measurement", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
